version: "3.8"

volumes:
    vol-emqx-data:
      name: foo-emqx-data
    vol-emqx-etc:
      name: foo-emqx-etc
    vol-emqx-log:
      name: foo-emqx-log


services: 
                                                                          
    mongo:
        container_name: mongo
        image: mongo:4.4
        restart: always
        environment: 
            TZ: "America/Mexico_City"
            MONGO_INITDB_ROOT_USERNAME: "devuser"
            MONGO_INITDB_ROOT_PASSWORD: "devpassword"
        
        volumes: 
            - ./mongodata:/data/db
            
        ports:
            - 27017:27017


    emqx:

        container_name: emqx
        image: emqx/emqx:4.2.3
        restart: always
        ports:
            - 18083:18083
            - 18084:18084
            - 1883:1883
            - 8883:8883
            - 8083:8083
            - 8084:8084
            - 8085:8081

    #    volumes: 
    #        - vol-emqx-data:/opt/emqx/data
    #        - vol-emqx-etc:/opt/emqx/etc
    #        - vol-emqx-log:/opt/emqx/log

        links: 
            - mongo

        extra_hosts: 
            - "localhost:192.168.1.84"

        environment: 
            
            EMQX_NAME: iotxprotech
            EMQX_HOST: 127.0.0.1

            TZ: "America/Mexico_City"

            # DEFAULT DASH PASS
            ## dashboard.default_user.login = admin
            EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "xprotech2021"
            
            # DEFAULT APP SECRET
            ## dashboard.default_user.login = admin
            EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "xprotech2021secret"

            EMQX_ALLOW_ANONYMOUS: "false"
            EMQX_NOMATCH: "deny"

            # MONGO CONNECTION
            EMQX_AUTH__MONGO__TYPE: single
            EMQX_AUTH__MONGO__SERVER: "mongo:27017"
            EMQX_AUTH__MONGO__POOL: 8
            
            EMQX_AUTH__MONGO__LOGIN: "devuser"
            EMQX_AUTH__MONGO__PASSWORD: "devpassword"
            EMQX_AUTH__MONGO__AUTH_SOURCE: admin
            
            EMQX_AUTH__MONGO__DATABASE: "IoTgl"
            EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"
            
            EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
            EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
            EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
            EMQX_AUTH__MONGO__SUPER_QUERY: "off"
            
            EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
            EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
            EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"
            
            ## ENABLE ACL QUERY
            ## ACCESS CONTROL LIST
            EMQX_AUTH__MONGO__ACL_QUERY: "on"
            EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
            EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

            EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"

            EMQX_LISTENER_TCP_EXTERNAL__MAX_CONNECTIONS: 1000

            
            
            

            
